function noline_data = DBNL_remove60hz(data, fs)
    filt60hz = designfilt('bandstopiir','FilterOrder',10, ...
               'HalfPowerFrequency1',59,'HalfPowerFrequency2',61, ...
               'DesignMethod','butter','SampleRate',fs);
    filt120hz = designfilt('bandstopiir','FilterOrder',10, ...
               'HalfPowerFrequency1',119,'HalfPowerFrequency2',121, ...
               'DesignMethod','butter','SampleRate',fs);
    filt180hz = designfilt('bandstopiir','FilterOrder',10, ...
               'HalfPowerFrequency1',179,'HalfPowerFrequency2',181, ...
               'DesignMethod','butter','SampleRate',fs);
    filt240hz = designfilt('bandstopiir','FilterOrder',10, ...
               'HalfPowerFrequency1',239,'HalfPowerFrequency2',241, ...
               'DesignMethod','butter','SampleRate',fs);
    filt300hz = designfilt('bandstopiir','FilterOrder',10, ...
               'HalfPowerFrequency1',299,'HalfPowerFrequency2',301, ...
               'DesignMethod','butter','SampleRate',fs);
noline_data = nan(size(data));
    parfor chan_num = 1:numel(data(:,1))
        temp_data_no60 = filtfilt(filt60hz,data(chan_num,:));
        temp_data_no120 = filtfilt(filt120hz,temp_data_no60);
        temp_data_no180 = filtfilt(filt180hz,temp_data_no120);
        temp_data_no240 = filtfilt(filt240hz,temp_data_no180);
        noline_data(chan_num,:) = filtfilt(filt300hz,temp_data_no240);
    end
end